# Terminal Emulator Settings
window:
  padding:
    x: 15
    y: 15
  scrolling:
    history: 15

# Setting zsh as the default shell
shell:
    program: /bin/zsh

# Font
font:
  normal:
    family: Fira Code
    style: Medium

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Italic

  bold_italic:
    family: Fira Code
    style: Bold Italic

  size: 10

# Colors
colors:
  # Default colors
  primary:
    background: '#151515'
    foreground: '#D0D0D0'

  # Normal colors
  normal:
    black:   '#151515'
    red:     '#AC4142'
    green:   '#90A959'
    yellow:  '#F4BF75'
    blue:    '#6A9FB5'
    magenta: '#AA759F'
    cyan:    '#75B5AA'
    white:   '#D0D0D0'

  # Bright colors
  bright:
    black:   '#252525'
    red:     '#AC4142'
    green:   '#90A959'
    yellow:  '#F4BF75'
    blue:    '#6A9FB5'
    magenta: '#AA759F'
    cyan:    '#75B5AA'
    white:   '#D0D0D0'

# Apply Settings without relaunching
live_config_reload: true
